---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    do_oauth_token: "{{ lookup('env', 'DO_API_TOKEN') }}"
    droplet_names_to_delete:
      - "tmp1.domain.tld"
      - "tmp2.domain.tld"
  
  tasks:
    - name: Get droplet details
      community.digitalocean.digital_ocean_droplet_info:
        oauth_token: "{{ do_oauth_token }}"
      register: droplets_info

    - name: Delete specified droplets
      community.digitalocean.digital_ocean_droplet:
        state: absent
        oauth_token: "{{ do_oauth_token }}"
        id: "{{ item.id }}"
      loop: "{{ droplets_info.data | selectattr('name', 'in', droplet_names_to_delete) | list }}"
      when: droplets_info.data is defined and droplets_info.data | length > 0
