---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    do_oauth_token: "{{ lookup('env', 'DO_API_TOKEN') }}"
    droplet_names_for_info:
      - "tmp1.domain.tld"
      - "tmp2.domain.tld"

  tasks:
    - name: Get droplet details
      community.digitalocean.digital_ocean_droplet_info:
        oauth_token: "{{ do_oauth_token }}"
      register: droplets_info

    - name: Print names and IDs of specified droplets
      debug:
        msg: "Droplet name: {{ item.name }}, ID: {{ item.id }}"
      loop: "{{ droplets_info.data }}"
      when: item.name in droplet_names_for_info

